add wave -noupdate /b06_testbench/stimuli/clk
add wave -noupdate /b06_testbench/stimuli/reset
add wave -noupdate /b06_testbench/stimuli/q
add wave -noupdate /b06_testbench/dut/clock
add wave -noupdate /b06_testbench/dut/cont_eql
add wave -noupdate /b06_testbench/dut/eql
add wave -noupdate /b06_testbench/dut/reset
add wave -noupdate /b06_testbench/dut/test_se
add wave -noupdate /b06_testbench/dut/test_si
add wave -noupdate /b06_testbench/dut/ackout
add wave -noupdate /b06_testbench/dut/cc_mux
add wave -noupdate /b06_testbench/dut/enable_count
add wave -noupdate /b06_testbench/dut/uscite
