add wave -noupdate /b10_testbench/stimuli/clk
add wave -noupdate /b10_testbench/stimuli/reset
add wave -noupdate /b10_testbench/stimuli/q
add wave -noupdate /b10_testbench/dut/v_in
add wave -noupdate /b10_testbench/dut/r_button
add wave -noupdate /b10_testbench/dut/g_button
add wave -noupdate /b10_testbench/dut/key
add wave -noupdate /b10_testbench/dut/start
add wave -noupdate /b10_testbench/dut/reset
add wave -noupdate /b10_testbench/dut/test
add wave -noupdate /b10_testbench/dut/rts
add wave -noupdate /b10_testbench/dut/rtr
add wave -noupdate /b10_testbench/dut/clock
add wave -noupdate /b10_testbench/dut/v_out
add wave -noupdate /b10_testbench/dut/cts
add wave -noupdate /b10_testbench/dut/ctr
